services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "soketi:6001"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file: .env
    ports:
      - "4040:4040"


  soketi:
    image: quay.io/soketi/soketi:1.0-16-debian
    ports:
      - "6001:6001"
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY}
      SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
      SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET}
    volumes:
      - ./soketi-data:/data  # Optional: Persist Soketi data
    mem_limit: 256m # Limit memory to 256 MB

volumes:
  soketi-data: