# Dockerfile
FROM quay.io/soketi/soketi:1.0-16-debian

# Environment variables for Soketi
ENV SOKETI_DEBUG=0
ENV SOKETI_DEFAULT_APP_KEY='iijdsjkanidnasqw9rqw'
ENV SOKETI_DEFAULT_APP_ID='4712912'
ENV SOKETI_DEFAULT_APP_SECRET='jsnfaoicfoapjfjpqef'
