services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "soketi:6001"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file: .env
    ports:
      - "4040:4040"


  soketi:
    build:
      context: .
      dockerfile: Dockerfile.soketi
    ports:
      - "6001:6001"  # Map WebSocket port
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_KEY: "iijdsjkanidnasqw9rqw"
      SOKETI_DEFAULT_APP_ID: "4712912"
      SOKETI_DEFAULT_APP_SECRET: "jsnfaoicfoapjfjpqef"
    volumes:
      - ./soketi-data:/data  # Optional: Persist Soketi data
